# Use postgres/example user/password credentials
version: '3.1'

services:
  my-java-container:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080

  db:
    image: postgres:12.4-alpine
    # restart: always
    environment:
      #- POSTGRES_DB: employees
      - POSTGRES_PASSWORD: hello1234
    volumes:
      - ~/datadir:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9090:8080
